### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by GeorgLink** [denali-design/denali-site#140]
The top two entries in the help menu are leading to a 404 error page on GitHub. See screenshot:

![Screen Shot 2020-09-29 at 3 20 19 PM](https://user-images.githubusercontent.com/8862021/94611637-a353d780-0267-11eb-9b51-7f8086354680.png)

Sorry, if this repo is the wrong place for reporting website issues.

**Comment by chasturansky** [comment]
Thank you for catching that. If you need to make a feature request do so [here](https://github.com/denali-design/denali-site/issues/new?labels=feature-request). We are currently working on our 2020 Q4 roadmap so that link should point to our milestones page [here](https://github.com/denali-design/denali-site/milestones?state=open).

**Comment by GeorgLink** [comment]
Thanks for fixing this @chasturansky !
