### ISSUE TITLE
Beta V2 Site Visual Updates

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-site#90]
Alignment issue
<img width="407" alt="Screen Shot 2020-04-17 at 5 44 34 PM" src="https://user-images.githubusercontent.com/15337851/79623872-51613000-80d3-11ea-93a7-e811972cd5da.png">

Denali theme code is not sticky on safari.

**Comment by chasturansky** [comment]
Update quote text to Helvetica black

<img width="1398" alt="Screen Shot 2020-04-17 at 5 55 08 PM" src="https://user-images.githubusercontent.com/15337851/79624118-98035a00-80d4-11ea-9c62-19dd170f47f7.png">

**Comment by chasturansky** [comment]
Resources icons on safari. Margins on resources.
![IMG_7516](https://user-images.githubusercontent.com/15337851/79671535-a35f8f80-817f-11ea-9d4b-f10703c71411.PNG)

**Comment by jazminorozco** [comment]
Update contribution footer to match new blue and revised homepage specific copy. New assets can be found in [Gallery](https://gallery.io/projects/MCHbtQVoQ2HCZcUj0AmKqIDu/files/MCHqlv5FtbLGVfWjb_KHb7_3). 

![Screen Shot 2020-04-19 at 12 30 14 PM](https://user-images.githubusercontent.com/20936130/79697790-9e5f1680-8239-11ea-9d10-391f34afc624.png)

**Comment by jazminorozco** [comment]
Update the copy in the partners second to correct typos. I also want to add to the sentence since the copy wasn't final. If the typos came from the mock, I apologize and I am ashamed lol Should read "From developer productivity tools to open source projects, Denali gives you the resources to bring your products to life"

![Screen Shot 2020-04-19 at 12 37 02 PM](https://user-images.githubusercontent.com/20936130/79697982-a9ff0d00-823a-11ea-8fab-5a76416a3dba.png)

**Comment by jazminorozco** [comment]
Don't know if we're looking at this as a nice to have but I had envisioned these as toggleable. So by default they are in the slideshow mode but clicking on a product can bring up that quote specifically. 

Also, "developer productivity" is spelled wrong here too

![Screen Shot 2020-04-19 at 12 41 21 PM](https://user-images.githubusercontent.com/20936130/79698107-86889200-823b-11ea-8974-690aa477557f.png)

**Comment by jazminorozco** [comment]
Update to Verizon Media? I believe open source gave us that ok a while back. 

![Screen Shot 2020-04-19 at 12 45 04 PM](https://user-images.githubusercontent.com/20936130/79698130-a4ee8d80-823b-11ea-9a5f-fe025bd4a8d8.png)

**Comment by jazminorozco** [comment]
I know this is very insignificant and not related to the whole site but it would be cool if this could anchor to the health care section when you click on it. Just saying, please don't kill me lol 

![Screen Shot 2020-04-19 at 12 46 38 PM](https://user-images.githubusercontent.com/20936130/79698181-0878bb00-823c-11ea-8827-e8f6fde5a048.png)

**Comment by jazminorozco** [comment]
Copy needs to be updated since it wasn't final. Should read:
```
**Everything you need to jump right in**
Whether you're a designer or developer get started with Denali in minutes using our handy guides and resources. 
```
![Screen Shot 2020-04-19 at 12 50 56 PM](https://user-images.githubusercontent.com/20936130/79698271-c69c4480-823c-11ea-9d99-a36c61bddcf8.png)

**Comment by jazminorozco** [comment]
All the button and link text needs to be updated to the bold weight as per the mock. Also for some reason the "what's new" link seems to be a different blue than the blue links in the article cards. 

![Screen Shot 2020-04-19 at 12 59 14 PM](https://user-images.githubusercontent.com/20936130/79698413-a28d3300-823d-11ea-9c8b-593703c7d98d.png)

![Screen Shot 2020-04-19 at 1 05 46 PM](https://user-images.githubusercontent.com/20936130/79698552-850c9900-823e-11ea-8719-334cd6e01c99.png)

**Comment by jazminorozco** [comment]
Update the header text since the copy was not final. Should read:

**Build and theme like never before**
Denali's themeable design system provides the ease of building with a framework without sacrificing your unique visual style. 

![Screen Shot 2020-04-19 at 1 16 24 PM](https://user-images.githubusercontent.com/20936130/79699085-f00b9f00-8241-11ea-88f2-74e3f79f9257.png)

**Comment by jazminorozco** [comment]
Edge of the dark theme container is revealed on larger desktop screen sizes (I expanded the chrome browser to 100% on my imac to get this).

![Screen Shot 2020-04-19 at 1 32 50 PM](https://user-images.githubusercontent.com/20936130/79699205-d9197c80-8242-11ea-9534-1fed7b54fbca.png)

**Comment by jazminorozco** [comment]
I don't know if this is the same as the alignment issue you commented above but in mobile/tablet views the text isn't aligned consistently. I also don't know if this is because of my not following the grid correctly. 

![Screen Shot 2020-04-19 at 1 58 04 PM](https://user-images.githubusercontent.com/20936130/79699715-00be1400-8246-11ea-8895-eb722bf3d655.png)

**Comment by jazminorozco** [comment]
I'd like to create an image that fits better in this space. Assuming we're ok with switching out the image when it hits the mobile breakpoint. 

![Screen Shot 2020-04-19 at 2 00 18 PM](https://user-images.githubusercontent.com/20936130/79699882-108a2800-8247-11ea-9a07-86a0c1b853e1.png)

**Comment by jazminorozco** [comment]
Black weight text renders oddly in safari 

![Screen Shot 2020-04-19 at 2 26 40 PM](https://user-images.githubusercontent.com/20936130/79700350-d706ec00-8249-11ea-83c8-6600cce632d4.png)

**Comment by jazminorozco** [comment]
Transition in components section isn't smooth in firefox

**Comment by jazminorozco** [comment]
Code snippet doesn't stay centered in safari mobile 
![IMG_2393](https://user-images.githubusercontent.com/20936130/79701317-f0f7fd00-8250-11ea-97c5-227e59151f03.png)

**Comment by chasturansky** [comment]
Items I will not fix right now.
- Toggling quotes
- Copyright
- Theme images
